//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsumoReceta
    {
        public int IdInsumoReceta { get; set; }
        public Nullable<int> IdReceta { get; set; }
        public Nullable<int> IdInsumo { get; set; }
        public Nullable<double> Cantidad { get; set; }
    
        public virtual Insumo Insumo { get; set; }
        public virtual Receta Receta { get; set; }
    }
}
