//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.PedidoProducto = new HashSet<PedidoProducto>();
        }
    
        public int IdPedido { get; set; }
        public string TipoEntrega { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<int> IdEstadoPedido { get; set; }
        public string Direccion { get; set; }
        public string NombreCliente { get; set; }
        public string TelefonoCliente { get; set; }
    
        public virtual EstadoPedido EstadoPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoProducto> PedidoProducto { get; set; }
    }
}
